# Data Science Workshop

# 2. NumPy for Scientific Computing

[**NumPy**](https://numpy.org/) is the fundamental package for *scientific computing* with Python. It contains a powerful *N-dimensional array object* that comes handy whenever we are dealing with numbers (compared with the plain Python list `[]`).

In [90]:
import numpy as np

[Here](https://www.w3resource.com/w3r_images/python-numpy-arrays-image.png) is a nice chart showing 1-d, 2-d and 3-d arrays.

## 2.1 Basics

NumPy's core object, `ndarray`, is the multidimensional array of elements of the same type (usually numbers).

In [91]:
a = np.array([[1,2,3],
              [4,5,6]])
type(a)

numpy.ndarray

In [92]:
a.ndim # number of dimensions

2

In [93]:
a.shape # dimensions

(2, 3)

In [94]:
a.dtype # data type

dtype('int64')

### Array Creation

There are 4 most common ways to create an array with NumPy.
- `np.array` creates an arbitrary array
- `np.zeros` creates an array of 0s
- `np.ones` creates an array of 1s (or any other constant with a multiplication)
- `np.arange` creates a range (analogous to the Python built-in `range`)

In [95]:
np.array(3.1, 4.7, 5.9) # WRONG

ValueError: only 2 non-keyword arguments accepted

In [96]:
b = np.array([3.1, 4.7, 5.9]) # RIGHT
print(b)
print(type(b))

[3.1 4.7 5.9]
<class 'numpy.ndarray'>


In [97]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [98]:
np.ones(4)*2

array([2., 2., 2., 2.])

In [99]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [100]:
np.arange(2,10,2)

array([2, 4, 6, 8])

In [101]:
np.arange(10,0,-2)

array([10,  8,  6,  4,  2])

In [102]:
np.linspace(0, 2, 9)

array([0.  , 0.25, 0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75, 2.  ])

We can print formatted `ndarray` using `print`:

In [103]:
print(np.arange(12).reshape(3,4))

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


### Arithmetic Operations

Arithmetic operators on NumPy arrays apply *elementwise*.

In [104]:
a = np.array([4,3,2,1])
b = np.arange(4)
print(a, b)

[4 3 2 1] [0 1 2 3]


In [105]:
a - b

array([ 4,  2,  0, -2])

In [106]:
b**2 # ** for power instead of ^

array([0, 1, 4, 9])

In [107]:
10 * np.cos(a)

array([-6.53643621, -9.89992497, -4.16146837,  5.40302306])

In [108]:
a > 2

array([ True,  True, False, False])

In [109]:
A = np.array([[1, 0],
              [0, 2]])
B = np.array([[2, 1],
              [1, 2]])
A * B # elementwise product

array([[2, 0],
       [0, 4]])

In [110]:
A.dot(B) # matrix (dot) product; alternatively use @

array([[2, 1],
       [2, 4]])

In [111]:
c = np.arange(12).reshape(3,4)
c

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [112]:
c.sum() # sum of all elements

66

In [113]:
c.sum(axis=0) # sum of each column

array([12, 15, 18, 21])

In [114]:
c.sum(axis=1) # sum of each row

array([ 6, 22, 38])

In [115]:
c.min(axis=1) # min of each row

array([0, 4, 8])

In [116]:
c.mean(axis=0) # mean of each column

array([4., 5., 6., 7.])

In [117]:
d = np.arange(3)
d

array([0, 1, 2])

In [118]:
np.exp(d) # exponential

array([1.        , 2.71828183, 7.3890561 ])

In [119]:
np.sqrt(d) # square root

array([0.        , 1.        , 1.41421356])

### Indexing and Iterating

Similar to Python lists, NumPy arrays can be indexed and iterated over.

In [120]:
# one-dimensional arrays
a = np.array([2, 3, 5, 7, 11, 13, 17, 19])
a

array([ 2,  3,  5,  7, 11, 13, 17, 19])

In [121]:
a[-2]

17

In [122]:
a[1:4]

array([3, 5, 7])

In [123]:
a[:5:2]

array([ 2,  5, 11])

In [124]:
a[::-1]

array([19, 17, 13, 11,  7,  5,  3,  2])

In [125]:
for i in a:
    print(i, end=' ')

2 3 5 7 11 13 17 19 

NumPy arrays can also be indexed by another array of integers or booleans.

In [126]:
i = np.array([2,2,5,1])
a[i]

array([ 5,  5, 13,  3])

In [127]:
b = a > 8
print(b)
a[b]

[False False False False  True  True  True  True]


array([11, 13, 17, 19])

In [128]:
# in short
a[a>8]

array([11, 13, 17, 19])

In [129]:
# multidimensional arrays
b = np.arange(12).reshape(3,4)
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [130]:
b[1,3]

7

In [131]:
b[1, 1:3]

array([5, 6])

In [132]:
b[:, 2]

array([ 2,  6, 10])

In [133]:
b[-1, :]

array([ 8,  9, 10, 11])

In [134]:
b[-1]

array([ 8,  9, 10, 11])

In [135]:
for row in b:
    print(row)

[0 1 2 3]
[4 5 6 7]
[ 8  9 10 11]


In [136]:
b.T # transpose

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [137]:
for column in b.T:
    print(column)

[0 4 8]
[1 5 9]
[ 2  6 10]
[ 3  7 11]


## 2.2 Manipulating Shapes

### Shaping

The **shape** of an `ndarray` can be changed without modifying the numbers in it.

In [138]:
a = np.arange(12).reshape(3,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [139]:
a.ravel() # flatten to a 1-d array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [140]:
a.reshape(2,6) # shape it to a 2 by 6 2-d array and return a copy

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11]])

In [141]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [142]:
a.T # transpose the array and return a copy

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [143]:
a.resize(2,6) # resize is same as reshape but changes the array w/o returning a copy

In [144]:
a

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11]])

### Stacking

- `row_stack` stacks 1-d arrays as rows
- `column_stack` stacks 1-d arrays as columns

In [145]:
a = np.array([1, 2, 3, 4])
b = np.array([5, 6, 7, 8])

In [146]:
np.row_stack((a,b))

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [147]:
np.column_stack((a,b))

array([[1, 5],
       [2, 6],
       [3, 7],
       [4, 8]])

- `vstack` stacks 2-d arrays *vertically* (row-wise)
- `hstack` stacks 2-d arrays *horizontally* (column-wise)

In [148]:
a = np.array([[1, 2], 
              [3, 4]])
b = np.array([[5, 6], 
              [7, 8]])

In [149]:
np.vstack((a, b))

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [150]:
np.hstack((a,b))

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

In [151]:
np.column_stack((a,b))

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

In [152]:
np.row_stack((a,b))

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

**Note**: simple 1-d arrays are *neither row nor column* vectors:

In [153]:
a = np.array([1,2,3])
print(a)
a.shape

[1 2 3]


(3,)

To explicitly define a **row** vector:

In [154]:
a = np.array([[1,2,3]])
print(a)
a.shape

[[1 2 3]]


(1, 3)

To explicitly define a **column** vector:

In [155]:
a = np.array([[1,2,3]]).T
print(a)
a.shape

[[1]
 [2]
 [3]]


(3, 1)

[`dstack`](https://numpy.org/devdocs/reference/generated/numpy.dstack.html#numpy.dstack) stacks higher dimensional arrays along third dimension (depth-wise). [`concatenate`](https://numpy.org/devdocs/reference/generated/numpy.concatenate.html#numpy.concatenate) is more general.

### Splitting

- `vsplit` spilts an array into multiple sub-arrays *vertically* (row-wise)
- `hsplit` stacks an array into multiple sub-arrays *horizontally* (column-wise)
- [`split`](https://numpy.org/devdocs/reference/generated/numpy.split.html) is more general for higher dimensional arrays

In [156]:
a = np.arange(32).reshape(4,8)
a

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30, 31]])

In [157]:
np.vsplit(a, 2)

[array([[ 0,  1,  2,  3,  4,  5,  6,  7],
        [ 8,  9, 10, 11, 12, 13, 14, 15]]),
 array([[16, 17, 18, 19, 20, 21, 22, 23],
        [24, 25, 26, 27, 28, 29, 30, 31]])]

In [158]:
np.hsplit(a, 2)

[array([[ 0,  1,  2,  3],
        [ 8,  9, 10, 11],
        [16, 17, 18, 19],
        [24, 25, 26, 27]]),
 array([[ 4,  5,  6,  7],
        [12, 13, 14, 15],
        [20, 21, 22, 23],
        [28, 29, 30, 31]])]

In [159]:
np.hsplit(a, [2,4,7])

[array([[ 0,  1],
        [ 8,  9],
        [16, 17],
        [24, 25]]),
 array([[ 2,  3],
        [10, 11],
        [18, 19],
        [26, 27]]),
 array([[ 4,  5,  6],
        [12, 13, 14],
        [20, 21, 22],
        [28, 29, 30]]),
 array([[ 7],
        [15],
        [23],
        [31]])]

## 2.3 Sorting and Searching

### Sorting

`sort` function can sort a 1-d array or a 2-d array along any axis.

In [160]:
a = np.array([3,2,4,1,9,6])
np.sort(a) # ascending order

array([1, 2, 3, 4, 6, 9])

In [161]:
np.sort(a)[::-1] # descending order

array([9, 6, 4, 3, 2, 1])

In [162]:
b = np.array([[10,40],
              [30,20]])
np.sort(b, axis = 0) # sort along first axis (row wise)

array([[10, 20],
       [30, 40]])

In [163]:
np.sort(b, axis=1) # sort along second axis (column wise)

array([[10, 40],
       [20, 30]])

In [164]:
np.sort(b, axis = None) # sort the flattened array

array([10, 20, 30, 40])

### Searching

`argmax` and `argmin` can be used to find the *indices* of the maximum / minimum values along an axis. (In case of multiple occurrences of the max/min values, the indices corresponding to the first occurrence are returned)

In [165]:
a = np.array([3,2,4,1,9,6])
print(np.argmax(a))
print(np.argmin(a))

4
3


In [166]:
b = np.array([[10,40,30],
              [30,20,50]])
np.argmax(b) # of the flattened array

5

In [167]:
np.argmax(b, axis=0) # along the first axis (row wise)

array([1, 0, 1])

In [168]:
np.argmax(b, axis=1) # along the second axis (column wise)

array([1, 2])

`amax` and `amin` can be used to return the maximum / minimum values instead of the indices.

In [169]:
np.amax(b, axis=1)

array([40, 50])

In [170]:
np.amin(b, axis=0)

array([10, 20, 30])

## Exercise

##### [Chinese Remainder Theorem](https://en.wikipedia.org/wiki/Chinese_remainder_theorem)

There are certain things whose number is unknown. If we count them by threes, we have two left over; by fives, we have three left over; and by sevens, two are left over. How many things are there?

Write a function `CRT(limit)` that returns all such numbers within the given function argument (limit). Test it with `CRT(500)`.

In [171]:
def CRT(limit):
    seq = np.arange(limit) 
    test = (seq % 3 == 2) & (seq % 5 == 3) & (seq % 7 == 2)
    return seq[test]
CRT(500)

array([ 23, 128, 233, 338, 443])

Use NumPy to create a 3 by 5 2-d array filled with 2 (integer, not float).

In [172]:
twos = np.ones((3,5), dtype=int)*2
twos

array([[2, 2, 2, 2, 2],
       [2, 2, 2, 2, 2],
       [2, 2, 2, 2, 2]])

Create a 3 by 2 2-d array filled with 0. Then stack it to the left of the above array.

In [173]:
zeros = np.zeros((3,2), dtype=int)
np.hstack((zeros, twos))

array([[0, 0, 2, 2, 2, 2, 2],
       [0, 0, 2, 2, 2, 2, 2],
       [0, 0, 2, 2, 2, 2, 2]])